import '~/styles/globals.css'

import { GeistSans } from 'geist/font/sans'
import { type Metadata } from 'next'

import FullScreenBackground from '~/components/FullScreenWrapperBackground'

export const metadata: Metadata = {
  title: '言葉の蜂',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <FullScreenBackground imageAlt="言葉の蜂 logo">
          {children}
        </FullScreenBackground>
      </body>
    </html>
  )
}
